### ISSUE TITLE
[radiant] How to pre-add data and start only the data mode

### ISSUE THREAD

**Issue by diraol** [radiant-rstats/docker#19]
Hi!

I've been reading the repo documentation and source code, but I couldn't find a way to use the radiant docker container in a way that I can select the `state.rda` file I want to be preloaded into Radiant. This data file could be shared via shared volumes with the container.

Also, I'd like to be able to run radiant only with the `data` mode, would that be possible? (`radiant.data("/mydata.state.rda")`).

Thank you for your attention!

**Comment by vnijs** [comment]
radiant.data::radiant.data("~/path-to-my-state-file.state.rda") should work. The docker container mounts your host OS so "~" would be your PC/mac home directory
