### ISSUE TITLE
jupyter notebook loading older version of a package

### ISSUE THREAD

**Issue by akshayreddykotha** [radiant-rstats/docker#23]
I tried to install a package locally.

By running, ```pip3 list```, I can see that the latest version is installed. But when I do:

```
import package
print(package.__version__)
```
I see an older version. 

Any insights on where the packages are installed within the docker environment (when I use ```pip3 install --user package)``` .

**Comment by vnijs** [comment]
If you are using a recent version of the docker container you can use the "clean" command from a terminal to remove any locally installed packages. Locally installed packages would be in `~/.rsm-msba/bin` or `~/.rsm-msba/lib` `~/.rsm-msba/share`

If you want to see where an imported package is, you can use the `__file__` attribute. See example below.

```
❯ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrsm
>>> pyrsm.__file__
'/usr/local/lib/python3.8/dist-packages/pyrsm/__init__.py'
>>>
```
