### ISSUE TITLE
Failure to install the "Windows Terminal" and Docker Desktop

### ISSUE THREAD

**Issue by Yibowang97** [radiant-rstats/docker#29]
after i entered the two-line code on Powershell, the information appears as on the image
![06b50218cf2190042defc9c2dcd19f0](https://user-images.githubusercontent.com/85983767/122167868-6a2cb900-ce30-11eb-9b3c-4c772d24c828.jpg)
I'm super confused and don't know how to fix this.

**Comment by vnijs** [comment]
I'll close this issue and we can continue the discussion on the class Piazza site.
