### ISSUE TITLE
https and plot server

### ISSUE THREAD

**Issue by notacustomdev** [radiant-rstats/docker#60]
Hi,

in case one needs to serve the GUI over https, what would then be way to configure ssl? In addition, how can one overwrite the standard behaviour (data sources, reduce the number of menu), keeping the dockerized structure?

**Comment by vnijs** [comment]
You can run the image/container on a laptop/desktop. You could try jupyterhub on server and use docker spawner to serve up the image. Works well. That part is managed but an IT partner on campus, however, so I don't know the details. Perhaps you can start with the below. We use both (1) local install and (2) jupyterhub for our students so they have access to a backup as needed and they can also have access to the computing platform after the graduate

https://tljh.jupyter.org/en/latest/

You can add datasources if you create a new image derived FROM this one. However, the way the launch script works now, you can mount the users home directory and just share data with other (e.g., through Dropbox or similar).

If you want fewer options you would have to dive into the launch scripts and edit it as you want
