### ISSUE TITLE
Unable to connect to service when adding custom users users

### ISSUE THREAD

**Issue by titansmc** [radiant-rstats/docker#8]
Hi,
I was using your image and it worked excellent, but now we have integrated z2jh with NFS mounts and so on, so we need to add custom /etc/passwd and /etc/groups to the image. So rebuilding your image like this, trows the Unable to connect error after 10s, roughly.

```
17:31 # cat rsm-jupyterhub/Dockerfile 
FROM vnijs/rsm-jupyterhub:latest

ADD ./passwd /etc/passwd
ADD ./group /etc/group

USER $NB_UID

```
![image](https://user-images.githubusercontent.com/8192096/94035039-f1c62980-fdc2-11ea-9282-46b393466b7e.png)

Do you have any idea about what I could  be doing wrong?

Cheers.

**Comment by vnijs** [comment]
This might just be an Rstudio issue that could be resolved by removing ~/.rstudio but could also be a permission issue. You would have to check the logs to see if there is anything useful there

**Comment by vnijs** [comment]
Closing since no further information was provided. I hope everything works now. If not, please create a new issue.

**Comment by titansmc** [comment]
sorry, after mounting NFS home all went fine

**Comment by vnijs** [comment]
Great. Thanks for the update @titansmc
